name: Releases Taplo

on:
  push:
    tags:
      - release-*
  workflow_dispatch:

jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      cli: ${{ steps.cli.outputs.version || '' }}
      vscode-ext: ${{ steps.vscode-ext.outputs.version || '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve release version
        if: startsWith(github.ref, 'refs/tags/release-taplo-cli-0')
        run: echo "version=$(echo ${GITHUB_REF#refs/tags/release-taplo-cli-})" >> $GITHUB_OUTPUT
        id: cli
      - name: Retrieve release version
        if: startsWith(github.ref, 'refs/tags/release-even-better-toml-')
        run: echo "version=$(echo ${GITHUB_REF#refs/tags/release-even-better-toml-})" >> $GITHUB_OUTPUT
        id: vscode-ext

  cli_docker:
    runs-on: ubuntu-latest
    needs: ["wait_for_ci", "get_version"]
    if: startsWith(github.ref, 'refs/tags/release-taplo-cli-0')
    strategy:
      matrix:
        image:
          - file: docker/cli-alpine.Dockerfile
            tags: tamasfe/taplo:latest,tamasfe/taplo:${{ needs.get_version.outputs.cli }},tamasfe/taplo:${{ needs.get_version.outputs.cli }}-alpine
          - file: docker/cli-full-alpine.Dockerfile
            tags: tamasfe/taplo:full,tamasfe/taplo:${{ needs.get_version.outputs.cli }}-full,tamasfe/taplo:${{ needs.get_version.outputs.cli }}-full-alpine
    steps:
      - run: |
          echo "file: ${{ matrix.image.file }}"
          echo "tags: ${{ matrix.image.tags }}"

  publish_cli:
    name: Release Taplo CLI binaries
    needs: [get_version]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo gh release create --draft ${{ needs.get_version.outputs.cli }} --title \"Taplo CLI ${{ needs.get_version.outputs.cli }}\" --target $GITHUB_SHA taplo-windows-*/* taplo-macos-*/* taplo-linux-*/*

  publish_vscode_extension:
    name: Publish VSCode Extension
    needs: [get_version]
    if: startsWith(github.ref, 'refs/tags/release-even-better-toml-')
    runs-on: ubuntu-latest
    steps:
      - name: Publish Open VSX Extension
        run: echo ovsx publish --baseImagesUrl https://raw.githubusercontent.com/tamasfe/taplo/master/editors/vscode -p OPEN_VSX_TOKEN \"even-better-toml-${{ needs.get_version.outputs.vscode-ext }}.vsix\"
